/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author bukanjoker
 */
public class SidePanel extends javax.swing.JPanel {

    /**
     * Creates new form SidePanel
     */
    private boolean state = false;
    
    public SidePanel() {
        initComponents();
        init();
    }
    
    boolean getState() 
    {
        return false;
    }
    
    public void init() 
    {
        
    }

    public boolean isState() {
        return state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        data1 = new javax.swing.JRadioButton();
        data2 = new javax.swing.JRadioButton();
        data3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        start = new javax.swing.JToggleButton();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(230, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(data1);
        data1.setText("Data 1");
        jPanel1.add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));

        buttonGroup1.add(data2);
        data2.setText("Data 2");
        jPanel1.add(data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 28, -1, -1));

        buttonGroup1.add(data3);
        data3.setText("Data 3");
        jPanel1.add(data3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 28, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pilihan Data:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, 61));

        start.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 184, 85, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        if (start.isSelected())
        {
            start.setText("Stop");
        }
        else 
        {
            start.setText("Start");
        }
    }//GEN-LAST:event_startActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton data1;
    private javax.swing.JRadioButton data2;
    private javax.swing.JRadioButton data3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton start;
    // End of variables declaration//GEN-END:variables

    
}
